use smp;
SELECT count(*) AS result FROM smp.smp_user;
SELECT count(*) AS result FROM smp.smp_user WHERE state != 1;
SELECT count(*) AS result FROM smp.smp_user WHERE state = 1;
SELECT count(*) AS result FROM smp.smp_user WHERE TIMESTAMPDIFF(MINUTE, last_seen, UTC_TIMESTAMP()) <= 30;
SELECT count(*) AS result FROM smp.smp_user WHERE `joined` like '2012-04-03%';
SELECT numMmsReceivedTotal AS result FROM smp_instrumentation.soapproxy;
SELECT numMmsReceivedFailed AS result FROM smp_instrumentation.soapproxy;
SELECT numMmsReceivedNotEnoughInfo AS result FROM smp_instrumentation.soapproxy;
SELECT numMmsReceivedInternalError AS result FROM smp_instrumentation.soapproxy;
SELECT numMmsSendFailed AS result FROM smp_instrumentation.soapproxy;
SELECT numMmsSendTotal AS result FROM smp_instrumentation.soapproxy;
SELECT numSmsReceivedFailed AS result FROM smp_instrumentation.soapproxy;
SELECT numSmsReceivedTotal AS result FROM smp_instrumentation.soapproxy;
SELECT numSmsSendFailed AS result FROM smp_instrumentation.soapproxy;
SELECT numSmsSendTotal AS result FROM smp_instrumentation.soapproxy;
SELECT numWebRequestsTotal AS result FROM smp_instrumentation.web;
SELECT numWebLogonsFailed AS result FROM smp_instrumentation.web;
SELECT numWebLogonsTotal AS result FROM smp_instrumentation.web;
SELECT numWapRequestsTotal AS result FROM smp_instrumentation.web;
SELECT numWapLogonsFailed AS result FROM smp_instrumentation.wap;
SELECT numWapLogonsTotal AS result FROM smp_instrumentation.wap;
SELECT numChannelRequestsTotal AS result FROM smp_instrumentation.gateway;
SELECT numChannelRequestsFailed AS result FROM smp_instrumentation.gateway;
SELECT numChannelRequestsFailedNotChannel AS result FROM smp_instrumentation.gateway;
SELECT numChannelRequestsFailedNotUser AS result FROM smp_instrumentation.gateway;
SELECT connectionStatusGateway AS result FROM smp_instrumentation.sns;
SELECT connectionStatusFacebook AS result FROM smp_instrumentation.sns;
SELECT connectionStatusYoutube AS result FROM smp_instrumentation.sns;
SELECT connectionStatusFlickr AS result FROM smp_instrumentation.sns;
SELECT connectionStatusOrkut AS result FROM smp_instrumentation.sns;
SELECT connectionStatusTwitter AS result FROM smp_instrumentation.sns;
SELECT connectionStatusWordpress AS result FROM smp_instrumentation.sns;
SELECT connectionStatusPicasa AS result FROM smp_instrumentation.sns;
SELECT connectionStatusBlogger AS result FROM smp_instrumentation.sns;
SELECT numFacebookRequestsTotal AS result FROM smp_instrumentation.sns;
SELECT numFacebookRequestsFailed AS result FROM smp_instrumentation.sns;
SELECT queueSizeFacebook AS result FROM smp_instrumentation.sns;
SELECT numFacebookRequestsFailedInvalidCredentials AS result FROM smp_instrumentation.sns;
SELECT numFacebookRequestsFailedServiceUnavailable AS result FROM smp_instrumentation.sns;
SELECT numFacebookRequestsFailedAlbumFull AS result FROM smp_instrumentation.sns;
SELECT numFacebookRequestsFailedInvalidFiletype AS result FROM smp_instrumentation.sns;
SELECT numFacebookRequestsFailedTooManyPending AS result FROM smp_instrumentation.sns;
SELECT numFacebookRequestsFailedInsufficientPermissions AS result FROM smp_instrumentation.sns;
SELECT numFacebookRequestsFailedPresenceLimitReached AS result FROM smp_instrumentation.sns;
SELECT numFacebookRequestsFailedGeneralError AS result FROM smp_instrumentation.sns;
SELECT numYoutubeRequestsTotal AS result FROM smp_instrumentation.sns;
SELECT numYoutubeRequestsFailed AS result FROM smp_instrumentation.sns;
SELECT queueSizeYoutube AS result FROM smp_instrumentation.sns;
SELECT numTwitterRequestsTotal AS result FROM smp_instrumentation.sns;
SELECT numTwitterRequestsFailed AS result FROM smp_instrumentation.sns;
SELECT queueSizeTwitter AS result FROM smp_instrumentation.sns;
SELECT numPicasaRequestsTotal AS result FROM smp_instrumentation.sns;
SELECT numPicasaRequestsFailed AS result FROM smp_instrumentation.sns;
SELECT queueSizePicasa AS result FROM smp_instrumentation.sns;
SELECT numWordpressRequestsTotal AS result FROM smp_instrumentation.sns;
SELECT numWordpressRequestsFailed AS result FROM smp_instrumentation.sns;
SELECT queueSizeWordpress AS result FROM smp_instrumentation.sns;
SELECT numBloggerRequestsTotal AS result FROM smp_instrumentation.sns;
SELECT numBloggerRequestsFailed AS result FROM smp_instrumentation.sns;
SELECT queueSizeBlogger AS result FROM smp_instrumentation.sns

