use smp

# count of users distributed by number of friends 
SELECT 
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=1 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a1,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=2 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a2,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=3 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a3,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=4 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a4,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=5 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a5,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=6 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a6,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=7 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a7,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=8 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a8,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=9 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a9,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=10 and u.amis<20 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a10,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=20 and u.amis<30 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a20,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=30 and u.amis<40 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a30,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=40 and u.amis<50 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a40,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=50 and u.amis<60 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a50,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=60 and u.amis<70 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a60,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=70 and u.amis<80 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a70,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=80 and u.amis<90 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a80,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=90 and u.amis<100 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a90,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen,su.joined from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=100 and u.last_seen>'2011-10' and u.joined < '2011-09-15') as a100
;

# count of users distributed by number of friends 
SELECT 
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=1 and u.last_seen>'2011-10') as a1,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=2 and u.last_seen>'2011-10') as a2,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=3 and u.last_seen>'2011-10') as a3,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=4 and u.last_seen>'2011-10') as a4,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=5 and u.last_seen>'2011-10') as a5,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=6 and u.last_seen>'2011-10') as a6,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=7 and u.last_seen>'2011-10') as a7,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=8 and u.last_seen>'2011-10') as a8,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis=9 and u.last_seen>'2011-10') as a9,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=10 and u.amis<20 and u.last_seen>'2011-10') as a10,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=20 and u.amis<30 and u.last_seen>'2011-10') as a20,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=30 and u.amis<40 and u.last_seen>'2011-10') as a30,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=40 and u.amis<50 and u.last_seen>'2011-10') as a40,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=50 and u.amis<60 and u.last_seen>'2011-10') as a50,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=60 and u.amis<70 and u.last_seen>'2011-10') as a60,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=70 and u.amis<80 and u.last_seen>'2011-10') as a70,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=80 and u.amis<90 and u.last_seen>'2011-10') as a80,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=90 and u.amis<100 and u.last_seen>'2011-10') as a90,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis, su.last_seen from smp_contact_friend inner JOIN smp_user as su ON su.user_id=rel_user_id group by rel_user_id) as u where u.amis>=100 and u.last_seen>'2011-10') as a100
;

# count of users distributed by number of friends 
SELECT 
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis=1) as a1,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis=2) as a2,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis=3) as a3,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis=4) as a4,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis=5) as a5,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis=6) as a6,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis=7) as a7,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis=8) as a8,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis=9) as a9,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis>=10 and u.amis<20) as a10,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis>=20 and u.amis<30) as a20,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis>=30 and u.amis<40) as a30,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis>=40 and u.amis<50) as a40,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis>=50 and u.amis<60) as a50,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis>=60 and u.amis<70) as a60,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis>=70 and u.amis<80) as a70,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis>=80 and u.amis<90) as a80,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis>=90 and u.amis<100) as a90,
  (select count(u.rel_user_id) from (select rel_user_id,count(distinct rel_friend_id) as amis from smp_contact_friend group by rel_user_id) as u where u.amis>=100) as a100
;
