set @_startdate=(select date('2015-01-01'));
set @_enddate=(select date('2015-02-01'));

#source zzzMAU.sql
#source cc.sql
/**/
drop table if exists zzlog501;
create table zzlog501 ENGINE=MyISAM DATA DIRECTORY='/var/mysql-data/smp/' INDEX DIRECTORY='/var/mysql-data/smp/' select * from smp_usage_log where time>= '2015-01-01' and time < '2015-01-03'; 

insert into zzlog501 select * from smp_usage_log where time >= '2015-01-03 00:00:00' and time < '2015-01-10';
select now(),'start'; 
insert into zzlog501 select * from smp_usage_log where time >= '2015-01-10 00:00:00' and time < '2015-01-16';
insert into zzlog501 select * from smp_usage_log where time >= '2015-01-16 00:00:00' and time < '2015-01-17';
insert into zzlog501 select * from smp_usage_log where time >= '2015-01-17 00:00:00' and time < '2015-01-18';
insert into zzlog501 select * from smp_usage_log where time >= '2015-01-18 00:00:00' and time < '2015-01-20';
select sleep(9),'2015-01-20'; 
insert into zzlog501 select * from smp_usage_log where time >= '2015-01-20 00:00:00' and time < '2015-01-22';
/****/
insert into zzlog501 select * from smp_usage_log where time >= '2015-01-22 00:00:00' and time < '2015-01-23';
insert into zzlog501 select * from smp_usage_log where time >= '2015-01-23 00:00:00' and time < '2015-01-24';
insert into zzlog501 select * from smp_usage_log where time >= '2015-01-24 00:00:00' and time < '2015-01-25';
insert into zzlog501 select * from smp_usage_log where time >= '2015-01-25 00:00:00' and time < '2015-01-27';
select sleep(9); 
insert into zzlog501 select * from smp_usage_log where time >= '2015-01-27 00:00:00' and time < '2015-01-29';
insert into zzlog501 select * from smp_usage_log where time >= '2015-01-29 00:00:00' and time < '2015-01-30';
insert into zzlog501 select * from smp_usage_log where time >= '2015-01-30 00:00:00' and time < @_enddate;

select now(),'zzlog501 is created'; 
/*
create index time on zzlog501(time);
create index msisdn on zzlog501(msisdn);
/*****/

SELECT count(*) as regUsers, count(if(rel_operator_id=10,1,NULL)) as mx, count(if(rel_operator_id=18,1,NULL)) as br, count(if(rel_operator_id=20,1,NULL)) as ar, count(if(rel_operator_id=19,1,NULL)) as pe, count(if(rel_operator_id=24,1,NULL)) as cl, count(if(rel_operator_id=16,1,NULL)) as pa, count(if(rel_operator_id=14,1,NULL)) as do, count(if(rel_operator_id=15,1,NULL)) as co, count(if(rel_operator_id=26,1,NULL)) as gt, count(if(rel_operator_id=29,1,NULL)) as hn, count(if(rel_operator_id=27,1,NULL)) as sv, count(if(rel_operator_id=30,1,NULL)) as ni, count(if(rel_operator_id=31,1,NULL)) as pr, count(if(rel_operator_id=33,1,NULL)) as cr, count(if(rel_operator_id=21,1,NULL)) as ec, count(if(rel_operator_id=23,1,NULL)) as ur, count(if(rel_operator_id=22,1,NULL)) as py FROM smp_user where joined < @_enddate and state=1;

SELECT count(*) as activated, count(distinct if(rel_operator_id=10,msisdn,NULL)) as mx, count(distinct if(rel_operator_id=18,msisdn,NULL)) as br, count(distinct if(rel_operator_id=20,msisdn,NULL)) as ar, count(distinct if(rel_operator_id=19,msisdn,NULL)) as pe, count(distinct if(rel_operator_id=24,msisdn,NULL)) as cl, count(distinct if(rel_operator_id=16,msisdn,NULL)) as pa, count(distinct if(rel_operator_id=14,msisdn,NULL)) as do, count(distinct if(rel_operator_id=15,msisdn,NULL)) as co, count(distinct if(rel_operator_id=26,msisdn,NULL)) as gt, count(distinct if(rel_operator_id=29,msisdn,NULL)) as hn, count(distinct if(rel_operator_id=27,msisdn,NULL)) as sv, count(distinct if(rel_operator_id=30,msisdn,NULL)) as ni, count(distinct if(rel_operator_id=31,msisdn,NULL)) as pr, count(distinct if(rel_operator_id=33,msisdn,NULL)) as cr, count(distinct if(rel_operator_id=21,msisdn,NULL)) as ec, count(distinct if(rel_operator_id=23,msisdn,NULL)) as ur, count(distinct if(rel_operator_id=22,msisdn,NULL)) as py FROM smp_user where joined>@_startdate and joined <@_enddate and state=1;

#SELECT count(distinct msisdn) as MAU, count(distinct if(u.rel_operator_id=10,msisdn,NULL)) as mx, count(distinct if(u.rel_operator_id=18,msisdn,NULL)) as br, count(distinct if(u.rel_operator_id=20,msisdn,NULL)) as ar, count(distinct if(u.rel_operator_id=19,msisdn,NULL)) as pe, count(distinct if(u.rel_operator_id=24,msisdn,NULL)) as cl, count(distinct if(u.rel_operator_id=16,msisdn,NULL)) as pa, count(distinct if(u.rel_operator_id=14,msisdn,NULL)) as do, count(distinct if(u.rel_operator_id=15,msisdn,NULL)) as co, count(distinct if(u.rel_operator_id=26,msisdn,NULL)) as gt, count(distinct if(u.rel_operator_id=29,msisdn,NULL)) as hn, count(distinct if(u.rel_operator_id=27,msisdn,NULL)) as sv, count(distinct if(u.rel_operator_id=30,msisdn,NULL)) as ni, count(distinct if(u.rel_operator_id=31,msisdn,NULL)) as pr, count(distinct if(u.rel_operator_id=33,msisdn,NULL)) as cr, count(distinct if(u.rel_operator_id=21,msisdn,NULL)) as ec, count(distinct if(u.rel_operator_id=23,msisdn,NULL)) as ur, count(distinct if(u.rel_operator_id=22,msisdn,NULL)) as py FROM zzlog501 left join smp_user as u using(msisdn) where u.state=1;

SELECT count(*) as MAU, count(distinct if(rel_operator_id=10,msisdn,NULL)) as mx, count(distinct if(rel_operator_id=18,msisdn,NULL)) as br, count(distinct if(rel_operator_id=20,msisdn,NULL)) as ar, count(distinct if(rel_operator_id=19,msisdn,NULL)) as pe, count(distinct if(rel_operator_id=24,msisdn,NULL)) as cl, count(distinct if(rel_operator_id=16,msisdn,NULL)) as pa, count(distinct if(rel_operator_id=14,msisdn,NULL)) as do, count(distinct if(rel_operator_id=15,msisdn,NULL)) as co, count(distinct if(rel_operator_id=26,msisdn,NULL)) as gt, count(distinct if(rel_operator_id=29,msisdn,NULL)) as hn, count(distinct if(rel_operator_id=27,msisdn,NULL)) as sv, count(distinct if(rel_operator_id=30,msisdn,NULL)) as ni, count(distinct if(rel_operator_id=31,msisdn,NULL)) as pr, count(distinct if(rel_operator_id=33,msisdn,NULL)) as cr, count(distinct if(rel_operator_id=21,msisdn,NULL)) as ec, count(distinct if(rel_operator_id=23,msisdn,NULL)) as ur, count(distinct if(rel_operator_id=22,msisdn,NULL)) as py FROM smp_user where state=1 and last_seen > @_startdate;

#SELECT count(*) as activations, count(distinct if(rel_operator_id=10,msisdn,NULL)) as mx, count(distinct if(rel_operator_id=18,msisdn,NULL)) as br, count(distinct if(rel_operator_id=20,msisdn,NULL)) as ar, count(distinct if(rel_operator_id=19,msisdn,NULL)) as pe, count(distinct if(rel_operator_id=24,msisdn,NULL)) as cl, count(distinct if(rel_operator_id=16,msisdn,NULL)) as pa, count(distinct if(rel_operator_id=14,msisdn,NULL)) as do, count(distinct if(rel_operator_id=15,msisdn,NULL)) as co, count(distinct if(rel_operator_id=26,msisdn,NULL)) as gt, count(distinct if(rel_operator_id=29,msisdn,NULL)) as hn, count(distinct if(rel_operator_id=27,msisdn,NULL)) as sv, count(distinct if(rel_operator_id=30,msisdn,NULL)) as ni, count(distinct if(rel_operator_id=31,msisdn,NULL)) as pr, count(distinct if(rel_operator_id=33,msisdn,NULL)) as cr, count(distinct if(rel_operator_id=21,msisdn,NULL)) as ec, count(distinct if(rel_operator_id=23,msisdn,NULL)) as ur, count(distinct if(rel_operator_id=22,msisdn,NULL)) as py FROM zzlog501 where action= 7;
SELECT miscstr3 as SMSoMMS,count(*) as AMX, count( if(rel_operator_id=10,1,NULL)) as mx, count( if(rel_operator_id=18,1,NULL)) as br, count( if(rel_operator_id=20,1,NULL)) as ar, count(if(rel_operator_id=19,1,NULL)) as pe, count(if(rel_operator_id=24,1,NULL)) as cl, count(if(rel_operator_id=16,1,NULL)) as pa, count(if(rel_operator_id=14,1,NULL)) as do, count(if(rel_operator_id=15,1,NULL)) as co, count(if(rel_operator_id=26,1,NULL)) as gt, count(if(rel_operator_id=29,1,NULL)) as hn, count(if(rel_operator_id=27,1,NULL)) as sv, count(if(rel_operator_id=30,1,NULL)) as ni, count(if(rel_operator_id=31,1,NULL)) as pr, count(if(rel_operator_id=33,1,NULL)) as cr, count(if(rel_operator_id=21,1,NULL)) as ec, count(if(rel_operator_id=23,1,NULL)) as ur, count(if(rel_operator_id=22,1,NULL)) as py FROM zzlog501 where action= 16 group by miscstr3;
SELECT 1 as Uploads,count(*) as AMX, count( if(oid=10,1,NULL)) as mx, count( if(oid=18,1,NULL)) as br, count( if(oid=20,1,NULL)) as ar, count(if(oid=19,1,NULL)) as pe, count(if(oid=24,1,NULL)) as cl, count(if(oid=16,1,NULL)) as pa, count(if(oid=14,1,NULL)) as do, count(if(oid=15,1,NULL)) as co, count(if(oid=26,1,NULL)) as gt, count(if(oid=29,1,NULL)) as hn, count(if(oid=27,1,NULL)) as sv, count(if(oid=30,1,NULL)) as ni, count(if(oid=31,1,NULL)) as pr, count(if(oid=33,1,NULL)) as cr, count(if(oid=21,1,NULL)) as ec, count(if(oid=23,1,NULL)) as ur, count(if(oid=22,1,NULL)) as py FROM zzcontent where time >@_startdate and time <@_enddate;

#SELECT count(*) as wapUpload, count(if(rel_operator_id=10,1,NULL)) as mx, count(if(rel_operator_id=18,1,NULL)) as br, count(if(rel_operator_id=20,1,NULL)) as ar, count(if(rel_operator_id=19,1,NULL)) as pe, count(if(rel_operator_id=24,1,NULL)) as cl, count(if(rel_operator_id=16,1,NULL)) as pa, count(if(rel_operator_id=14,1,NULL)) as do, count(if(rel_operator_id=15,1,NULL)) as co, count(if(rel_operator_id=26,1,NULL)) as gt, count(if(rel_operator_id=29,1,NULL)) as hn, count(if(rel_operator_id=27,1,NULL)) as sv, count(if(rel_operator_id=30,1,NULL)) as ni, count(if(rel_operator_id=31,1,NULL)) as pr, count(if(rel_operator_id=33,1,NULL)) as cr, count(if(rel_operator_id=21,1,NULL)) as ec, count(if(rel_operator_id=23,1,NULL)) as ur, count(if(rel_operator_id=22,1,NULL)) as py FROM zzlog501 where action=3 and miscstr3= 'mobile';
SELECT count(*) as wapPresence, count(if(rel_operator_id=10,1,NULL)) as mx, count(if(rel_operator_id=18,1,NULL)) as br, count(if(rel_operator_id=20,1,NULL)) as ar, count(if(rel_operator_id=19,1,NULL)) as pe, count(if(rel_operator_id=24,1,NULL)) as cl, count(if(rel_operator_id=16,1,NULL)) as pa, count(if(rel_operator_id=14,1,NULL)) as do, count(if(rel_operator_id=15,1,NULL)) as co, count(if(rel_operator_id=26,1,NULL)) as gt, count(if(rel_operator_id=29,1,NULL)) as hn, count(if(rel_operator_id=27,1,NULL)) as sv, count(if(rel_operator_id=30,1,NULL)) as ni, count(if(rel_operator_id=31,1,NULL)) as pr, count(if(rel_operator_id=33,1,NULL)) as cr, count(if(rel_operator_id=21,1,NULL)) as ec, count(if(rel_operator_id=23,1,NULL)) as ur, count(if(rel_operator_id=22,1,NULL)) as py FROM zzlog501 where action= 2 AND miscstr3= 'mobile' AND miscid1= 0 ;
SELECT count(distinct msisdn) as wapMAU, count(distinct if(rel_operator_id=10,msisdn,NULL)) as mx, count(distinct if(rel_operator_id=18,msisdn,NULL)) as br, count(distinct if(rel_operator_id=20,msisdn,NULL)) as ar, count(distinct if(rel_operator_id=19,msisdn,NULL)) as pe, count(distinct if(rel_operator_id=24,msisdn,NULL)) as cl, count(distinct if(rel_operator_id=16,msisdn,NULL)) as pa, count(distinct if(rel_operator_id=14,msisdn,NULL)) as do, count(distinct if(rel_operator_id=15,msisdn,NULL)) as co, count(distinct if(rel_operator_id=26,msisdn,NULL)) as gt, count(distinct if(rel_operator_id=29,msisdn,NULL)) as hn, count(distinct if(rel_operator_id=27,msisdn,NULL)) as sv, count(distinct if(rel_operator_id=30,msisdn,NULL)) as ni, count(distinct if(rel_operator_id=31,msisdn,NULL)) as pr, count(distinct if(rel_operator_id=33,msisdn,NULL)) as cr, count(distinct if(rel_operator_id=21,msisdn,NULL)) as ec, count(distinct if(rel_operator_id=23,msisdn,NULL)) as ur, count(distinct if(rel_operator_id=22,msisdn,NULL)) as py FROM zzlog501 where miscstr3= 'mobile' ; 
SELECT miscstr3 as MMSPending,count(distinct msisdn) as AMX, count(distinct if(u.rel_operator_id=10,msisdn,NULL)) as mx, count(distinct if(u.rel_operator_id=18,msisdn,NULL)) as br, count(distinct if(u.rel_operator_id=20,msisdn,NULL)) as ar, count(distinct if(u.rel_operator_id=19,msisdn,NULL)) as pe, count(distinct if(u.rel_operator_id=24,msisdn,NULL)) as cl, count(distinct if(u.rel_operator_id=16,msisdn,NULL)) as pa, count(distinct if(u.rel_operator_id=14,msisdn,NULL)) as do, count(distinct if(u.rel_operator_id=15,msisdn,NULL)) as co, count(distinct if(u.rel_operator_id=26,msisdn,NULL)) as gt, count(distinct if(u.rel_operator_id=29,msisdn,NULL)) as hn, count(distinct if(u.rel_operator_id=27,msisdn,NULL)) as sv, count(distinct if(u.rel_operator_id=30,msisdn,NULL)) as ni, count(distinct if(u.rel_operator_id=31,msisdn,NULL)) as pr, count(distinct if(u.rel_operator_id=33,msisdn,NULL)) as cr, count(distinct if(u.rel_operator_id=21,msisdn,NULL)) as ec, count(distinct if(u.rel_operator_id=23,msisdn,NULL)) as ur, count(distinct if(u.rel_operator_id=22,msisdn,NULL)) as py FROM zzlog501 left join smp_user as u using(msisdn) where action= 16 and u.state=0 group by miscstr3;
SELECT count(*) as sbPosts, count(if(rel_operator_id=10,1,NULL)) as mx, count(if(rel_operator_id=18,1,NULL)) as br, count(if(rel_operator_id=20,1,NULL)) as ar, count(if(rel_operator_id=19,1,NULL)) as pe, count(if(rel_operator_id=24,1,NULL)) as cl, count(if(rel_operator_id=16,1,NULL)) as pa, count(if(rel_operator_id=14,1,NULL)) as do, count(if(rel_operator_id=15,1,NULL)) as co, count(if(rel_operator_id=26,1,NULL)) as gt, count(if(rel_operator_id=29,1,NULL)) as hn, count(if(rel_operator_id=27,1,NULL)) as sv, count(if(rel_operator_id=30,1,NULL)) as ni, count(if(rel_operator_id=31,1,NULL)) as pr, count(if(rel_operator_id=33,1,NULL)) as cr, count(if(rel_operator_id=21,1,NULL)) as ec, count(if(rel_operator_id=23,1,NULL)) as ur, count(if(rel_operator_id=22,1,NULL)) as py FROM zzlog501 where action=10 AND miscstr3= 'sb';
# the sbMAU first column represents the activated+inactivated accounts;

SELECT count(distinct msisdn) as sbMAU, count(distinct if(rel_operator_id=10,msisdn,NULL)) as mx, count(distinct if(rel_operator_id=18,msisdn,NULL)) as br, count(distinct if(rel_operator_id=20,msisdn,NULL)) as ar, count(distinct if(rel_operator_id=19,msisdn,NULL)) as pe, count(distinct if(rel_operator_id=24,msisdn,NULL)) as cl, count(distinct if(rel_operator_id=16,msisdn,NULL)) as pa, count(distinct if(rel_operator_id=14,msisdn,NULL)) as do, count(distinct if(rel_operator_id=15,msisdn,NULL)) as co, count(distinct if(rel_operator_id=26,msisdn,NULL)) as gt, count(distinct if(rel_operator_id=29,msisdn,NULL)) as hn, count(distinct if(rel_operator_id=27,msisdn,NULL)) as sv, count(distinct if(rel_operator_id=30,msisdn,NULL)) as ni, count(distinct if(rel_operator_id=31,msisdn,NULL)) as pr, count(distinct if(rel_operator_id=33,msisdn,NULL)) as cr, count(distinct if(rel_operator_id=21,msisdn,NULL)) as ec, count(distinct if(rel_operator_id=23,msisdn,NULL)) as ur, count(distinct if(rel_operator_id=22,msisdn,NULL)) as py FROM zzlog501 where action IN (9, 10, 11, 12) AND miscstr3= 'sb';

select date(time) as date, count(if(action=3,1,null)) as a3, count(if(action=4,1,null)) as a4, count(if(action=5,1,null)) as a5, count(if(action=6,1,null)) as a6, count(if(action=7,1,null)) as a7, count(if(action=8,1,null)) as a8, count(if(action=9,1,null)) as a9, count(if(action=10,1,null)) as a10, count(if(action=11,1,null)) as a11, count(if(action=12,1,null)) as a12, count(if(action=13,1,null)) as a13, count(if(action=14,1,null)) as a14, count(if(action=15,1,null)) as a15, count(if(action=16,1,null)) as a16, count(if(action=17,1,null)) as a17, count(if(action=18,1,null)) as a18 from zzlog501 group by date with rollup;

